name: Publish to npm

on:
  push:
    branches: [ publish ]
  pull_request:
    branches: [ publish ]

jobs:
  prebuild:
    runs-on: ${{ matrix.os }}
    if: >-  
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.head_commit.message, 'skip ci')

    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [10.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - name: Try to cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      if: runner.os != Windows
      run: SKIP_BUILD=1 npm ci

    - name: Install dependencies
      if: runner.os == Windows
      run: set SKIP_BUILD=1 && npm ci

    - name: Prebuild using prebuildify
      run: npm run prebuildify

    - name: Upload prebuilts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-prebuilt
        path: prebuilds
      
  publish:
    runs-on: ubuntu-latest
    needs: prebuild
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Get npm cache directory
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - name: Try to cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: SKIP_BUILD=1 npm ci

    - name: Transpile typescript
      run: npm run gen-js

    - name: Download prebuilts
      uses: actions/download-artifact@v2
      with:
        path: artifacts

    - name: List all prebuilts
      run: find prebuilds | sed -e 's;[^/]*/;|____;g;s;____|; |;g'

    - name: Publish to npm
      run: echo Not implemented!