name: Test functionality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    if: >-
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.head_commit.message, 'skip ci')

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get npm cache directory and npm cache hash key (Posix)
      if: runner.os != 'Windows'
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
        echo "::set-output name=hashkey::$(shasum -a 256 package-lock.json | cut -d " " -f 1)"

    - name: Get npm cache directory and npm cache hash key (Windows)
      if: runner.os == 'Windows'
      id: npm-cache
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
        echo "::set-output name=hashkey::$(Get-FileHash package-lock.json | Select-Object -ExpandProperty Hash)"

    - name: Try to cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ steps.npm-cache.outputs.hashkey }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
