name: Test functionality

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    if: >-
      !contains(github.event.head_commit.message, 'ci skip') &&
      !contains(github.event.head_commit.message, 'skip ci')

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get npm cache directory and npm cache hash key (Posix)
      if: runner.os != 'Windows'
      run: |
        echo "npm_cache_dir=$(npm config get cache)" >> $GITHUB_ENV
        echo "npm_cache_hash=$(shasum -a 256 package-lock.json | cut -d " " -f 1)" >> $GITHUB_ENV

    - name: Get npm cache directory and npm cache hash key (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "npm_cache_dir=$(npm config get cache)" >> ${{ env.GITHUB_ENV }}
        echo "npm_cache_hash=$(Get-FileHash package-lock.json | Select-Object -ExpandProperty Hash)" >> ${{ env.GITHUB_ENV }}

    - name: Try to cache
      uses: actions/cache@v2
      with:
        path: ${{ env.npm_cache_dir }}
        key: ${{ runner.os }}-node-${{ env.npm_cache_hash }}

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
